##
##  Agentic Software Engineering (ASE)
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   static code analysis (linting)
lint
    eslint --config etc/eslint.mjs src/*.tsx src/screens/*.tsx

#   static code analysis (linting) with file watching
lint-watch
    nodemon --exec "npm start lint" --watch src --ext tsx

#   code compilation/transpiling (building) with file watching
build-watch
    nodemon --exec "npm start build" --watch src --ext tsx

#   build entire project
build : lint build-cmd

#   build command program
build-cmd
    tsc --project etc/tsc.json

#   remove regularly built files
clean
    shx rm -rf dst

#   remove all built files
clean-dist : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules
